"""new data

Revision ID: 2bf377cf0ac8
Revises: e2f8f4c8ae75
Create Date: 2024-05-06 15:48:02.766074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf377cf0ac8'
down_revision = 'e2f8f4c8ae75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
