"""empty message

Revision ID: 72d7af7310fb
Revises: e51a196c6e40
Create Date: 2024-05-06 11:58:42.861617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d7af7310fb'
down_revision = 'e51a196c6e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=False))
        batch_op.drop_column('companyName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyName', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
